// plugins/database/mysql/ui/src/components/QueryEditor.tsx
import React, { useState } from "react";
import { usePluginContext } from "@baibai/plugin-core";
import { Space } from "antd";
import MonacoEditor from "react-monaco-editor";

const QueryEditor: React.FC = () => {
  const {
    i18n: { t },
    components: { Button },
  } = usePluginContext();
  const [sql, setSql] = useState("");

  const handleExecute = () => {
    // 执行查询
  };

  const editorOptions = {
    minimap: { enabled: false },
    scrollBeyondLastLine: false,
    fontSize: 14,
  };

  return (
    <div className="query-editor">
      <div className="toolbar mb-2">
        <Space>
          <Button type="primary" onClick={handleExecute}>
            {t("editor.execute")}
          </Button>
        </Space>
      </div>
      <MonacoEditor
        language="sql"
        value={sql}
        onChange={setSql}
        options={editorOptions}
        height="200px"
      />
    </div>
  );
};

export default QueryEditor;

// plugins/mysql/ui/src/components/QueryEditor.tsx
import { defineComponent, ref } from "vue";
import { usePluginContext } from "@baibai/plugin-core";

export default defineComponent({
  name: "QueryEditor",
  setup() {
    const {
      i18n: { t },
      components: { Space, Button, Input },
    } = usePluginContext();
    const sql = ref("");

    const handleExecute = () => {
      // ...
    };

    return () => (
      <div class="query-editor">
        <div class="toolbar">
          <Space>
            <Button type="primary" onClick={handleExecute}>
              {t("editor.execute")}
            </Button>
          </Space>
        </div>
        <Input.TextArea
          v-model={sql.value}
          class="editor"
          placeholder={t("editor.placeholder")}
          autoSize={{ minRows: 4, maxRows: 10 }}
        />
      </div>
    );
  },
});
